development:
  app_id: <%= ENV["PARSE_RAILS_OAUTH_APP_ID"] %>
  master_key: <%= ENV["PARSE_RAILS_OAUTH_MASTER_KEY"] %>

test:
  app_id: <%= ENV["PARSE_RAILS_OAUTH_APP_ID"] %>
  master_key: <%= ENV["PARSE_RAILS_OAUTH_MASTER_KEY"] %>

production:
  app_id: <%= ENV["PARSE_RAILS_OAUTH_APP_ID"] %>
  master_key: <%= ENV["PARSE_RAILS_OAUTH_MASTER_KEY"] %>